version: '3'
services:
  redtetris_frontend:
    container_name: redtetris_frontend
    build: ./frontend/
    restart: unless-stopped
    environment:
      FRONT_PORT: ${FRONT_PORT}
      VITE_API_URL: ${VITE_API_URL}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
      VITE_GOOGLE_AUTH_URI: ${VITE_GOOGLE_AUTH_URI}
      VITE_GOOGLE_REDIRECT_URI: ${VITE_GOOGLE_REDIRECT_URI}
    ports:
      - '${FRONT_PORT}:${FRONT_PORT}'
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules

  redtetris_backend:
    container_name: redtetris_backend
    build: ./backend/
    restart: unless-stopped
    environment:
      BACK_PORT: ${BACK_PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    ports:
      - '${BACK_PORT}:${BACK_PORT}'
    volumes:
      - ./backend:/home/node/app/backend
      - /home/node/app/backend/node_modules
    depends_on:
      - redtetris_postgres

  redtetris_postgres:
    container_name: redtetris_postgres
    image: postgres:16.1
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    # ports:
    #   - ${POSTGRES_PORT}:5432

volumes:
  postgres:
